### ISSUE TITLE
please include highlightjs.pack.js in @highlightjs/cdn-assets npm package

### ISSUE THREAD

**Issue by rjminchuk** [highlightjs/cdn-release#5]
I'd like to include [terraform languages support](https://github.com/highlightjs/highlightjs-terraform) in my web application, but the highlightjs.pack.js file is not included in the @highlightjs/cdn-assets npm package.

**Comment by joshgoebel** [comment]
Use `highlightjs.min.js`, same thing.  `pack` is only an artifact of the old website download process.

**Comment by joshgoebel** [comment]
Sorry just now seeing this as I wasn't subscribed to ALL issues here.

**Comment by rjminchuk** [comment]
ty!
